/*
 * generated by Xtext
 */
package rs.demsys.vhdl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VhdlRuntimeModule extends rs.demsys.vhdl.AbstractVhdlRuntimeModule {

}
