/*
 * generated by Xtext
 */
package rs.demsys.vhdl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class VhdlStandaloneSetup extends VhdlStandaloneSetupGenerated{

	public static void doSetup() {
		new VhdlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

