/*
 * generated by Xtext
 */
package rs.demsys.vhdl.ui.contentassist

import rs.demsys.vhdl.ui.contentassist.AbstractVhdlProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class VhdlProposalProvider extends AbstractVhdlProposalProvider {
}
