/*
 * generated by Xtext
 */
package rs.demsys.vhdl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class VhdlUiModule extends rs.demsys.vhdl.ui.AbstractVhdlUiModule {
	public VhdlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
